collections_dir: _collections

collections:
  pages:
    output: true
    permalink: /:path
  services:
    output: true
    permalink: /uslugi/:path/

# Custom configuration
images_dir: /assets/img/
