collections_dir: _collections

collections:
  pages:
    output: true
    permalink: /:path
  services:
    output: true
    permalink: /uslugi/:path/

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"

# Custom configuration
images_dir: /assets/img/
