collections_dir : _collections

collections:
  services:
    output: true
    permalink: /uslugi/:path/

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "article"

sass:
  style: compressed
