collections_dir : _collections

collections:
  services:
    output: true
    permalink: /uslugi/:path/

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"

sass:
  style: compressed

plugins:
  - octopress-minify-html
  - jekyll-pages-directory
