collections:
  services:
    output: true
    permalink: /uslugi/:path/

collections_dir : _collections

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"

jekyll-minifier:
  uglifier_args:
    harmony: true
