collections:
  services:
    output: true
    permalink: /uslugi/:path/

collections_dir : _collections

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"

plugins:
  - jekyll-sitemap

url: "https://hydraulik-instalator.stargard.pl"
